### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by sredbull** [Kocal/jsdoc-vuejs#13]
having the following issue when I set followImport: true

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'src/mixins/emitEvent'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at evalmachine.<anonymous>:11:18
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at module.exports (/jsdoc/lib/vueComponentPrototypeExtractor.js:22:10)
    at exports.Parser.beforeParse (/jsdoc/index.js:20:47)
    at emitOne (events.js:115:13)
    at exports.Parser.emit (events.js:210:7)
    at exports.Parser.Parser._parseSourceCode (/node_modules/jsdoc/lib/jsdoc/src/parser.js:248:14)
    at exports.Parser.Parser.parse (/node_modules/jsdoc/lib/jsdoc/src/parser.js:179:18)
    at Object.module.exports.cli.parseFiles (/node_modules/jsdoc/cli.js:370:42)
    at module.exports.cli.main (/node_modules/jsdoc/cli.js:239:14)
    at Object.module.exports.cli.runCommand (/node_modules/jsdoc/cli.js:189:5)
    at /node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/node_modules/jsdoc/jsdoc.js:106:3)

```

And with false:

```
Ignore importing src/mixins/emitEvent
Ignore importing src/components/General/Elements/Modal.vue
Ignore importing src/services/AuthService
Ignore importing vuelidate/lib/validators
Ignore importing quasar
evalmachine.<anonymous>:32
    QCard: _quasar.QCard,
                  ^

TypeError: Cannot read property 'QCard' of undefined
    at evalmachine.<anonymous>:32:19
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at module.exports (/jsdoc/lib/vueComponentPrototypeExtractor.js:22:10)
    at exports.Parser.beforeParse (/jsdoc/index.js:20:47)
    at emitOne (events.js:115:13)
    at exports.Parser.emit (events.js:210:7)
    at exports.Parser.Parser._parseSourceCode (/node_modules/jsdoc/lib/jsdoc/src/parser.js:248:14)
    at exports.Parser.Parser.parse (/node_modules/jsdoc/lib/jsdoc/src/parser.js:179:18)
    at Object.module.exports.cli.parseFiles (/node_modules/jsdoc/cli.js:370:42)
    at module.exports.cli.main (/node_modules/jsdoc/cli.js:239:14)
```

It breaks at the components: {} and validations: {} part in export default {}

**Comment by Kocal** [comment]
Can you provide some code?

**Comment by sredbull** [comment]
`<script>
  import emitEvent from 'src/mixins/emitEvent'
  import Modal from 'src/components/General/Elements/Modal.vue'
  import { AuthService } from 'src/services/AuthService'
  import {required, email} from 'vuelidate/lib/validators'
  import {
    QCard,
    QCardMain,
    QCardTitle,
    QInput,
    QField,
    QRating,
    QSelect,
    Toast
  } from 'quasar'

  export default {
    name: 'password-forgot',
    mixins: [emitEvent],
    components: {
      Modal,
      QCard,
      QCardMain,
      QCardTitle,
      QInput,
      QField,
      QSelect,
      QRating,
      Toast
    },
    data () {
      return {
        feedbackItem: {},
        selectOptions: [],
        user: [],
        validationError: false
      }
    },
    validations: {
      user: {
        email: {
          required,
          email
        }
      }
    },
    methods: {`

**Comment by Kocal** [comment]
Mmmh, are you sure about your imports ?

Shouldn't be something like that? : 
```js
import emitEvent from './src/mixins/emitEvent'
import Modal from './src/components/General/Elements/Modal.vue'
import { AuthService } from './src/services/AuthService'
```

**Comment by sredbull** [comment]
Nope, results in same error

**Comment by Kocal** [comment]
Mmmh... I don't really know... 
It's « okay » that's failing if `followImports` is set to `false`, but it shouldn't fail if `followImports` is `true`.

Can you give me your project tree and content of `src/mixins/emitEvent.js` ?

**Comment by sredbull** [comment]
It looks like there is an issue with the PATH, when I set my imports to use full links to errors go away one by one but the node_modules plugins still fail to load.

**Comment by sredbull** [comment]
<img width="391" alt="screen shot 2017-11-13 at 22 39 03" src="https://user-images.githubusercontent.com/8779177/32750641-97214848-c8c3-11e7-9fe6-a302b26c7761.png">

**Comment by Kocal** [comment]
Uh? Why do you have a `jsdoc` folder in your project root?

**Comment by sredbull** [comment]
<img width="773" alt="screen shot 2017-11-13 at 22 41 50" src="https://user-images.githubusercontent.com/8779177/32750747-e95251c0-c8c3-11e7-818d-30ec2f786747.png">

**Comment by sredbull** [comment]
I was testing things out with it, let me try the node_modules one to be sure

**Comment by sredbull** [comment]
unfortunately the same result
