### ISSUE TITLE
Error when use vuex

### ISSUE THREAD

**Issue by EdmundTheRadiance** [Kocal/jsdoc-vuejs#47]
`vue.use(vuex)`
when use vuex, this may be some problem:

evalmachine.<anonymous>:21
_vue2.default.use(_vuex2.default);
                      ^

TypeError: Cannot read property 'use' of undefined
    at evalmachine.<anonymous>:21:14
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at module.exports (D:\work\test\node_modules\jsdoc-vuejs\lib\vueComponentPro
totypeExtractor.js:22:10)
    at exports.Parser.beforeParse (D:\work\test\node_modules\jsdoc-vuejs\index.j
s:20:47)
    at emitOne (events.js:115:13)
    at exports.Parser.emit (events.js:210:7)
    at exports.Parser.Parser._parseSourceCode (D:\work\test\node_modules\jsdoc\l
ib\jsdoc\src\parser.js:248:14)
    at exports.Parser.Parser.parse (D:\work\test\node_modules\jsdoc\lib\jsdoc\sr
c\parser.js:179:18)
    at Object.module.exports.cli.parseFiles (D:\work\test\node_modules\jsdoc\cli
.js:370:42)
    at module.exports.cli.main (D:\work\test\node_modules\jsdoc\cli.js:239:14)

**Comment by Kocal** [comment]
How did you setup jsdoc-vuejs and Vuex? 
Can you provide some code please?

I made a small repo that use Vuex and jsdoc-vuejs, but I didn't encountered any problems: 
- repo: https://github.com/Kocal/jsdoc-example-with-vuex
- docs: https://kocal.github.io/jsdoc-example-with-vuex/Vue_App.html

**Comment by EdmundTheRadiance** [comment]
I think it is caused by setting followImports false.
But when I set it true, some modules can't be found, because I use alias in file path like
`import Util from '@/lib/util'`
and webpack will resolve '@' to my project root path's absolute paths, it can't work in jsdoc parsing.
I think I will try to find a way to solve it.
