### ISSUE TITLE
Error finding modules import with an alias and extensions resolve in Webpack

### ISSUE THREAD

**Issue by MyrtoM** [Kocal/jsdoc-vuejs#7]
While running jsdoc command, the error 'Error: Cannot find module 'components/base/header/Header' is thrown because I'm using the "@" alias and the rules of resolve extentions of my Webpack config. So I import the child components with that kind of pattern in my Vue components : 
_import Header from '@/components/base/header/Header'_

Is it expected that you will consider such rules in the future ?

Thank you for this plugin

`Error: Cannot find module 'components/base/header/Header'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at evalmachine.<anonymous>:11:15
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at module.exports (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc-vuejs/lib/vueComponentPrototypeExtractor.js:20:10)
    at beforeParse (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc-vuejs/index.js:20:47)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Parser._parseSourceCode (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc/lib/jsdoc/src/parser.js:248:14)
    at Parser.parse (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc/lib/jsdoc/src/parser.js:179:18)
    at Object.module.exports.cli.parseFiles (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc/cli.js:370:42)
    at module.exports.cli.main (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc/cli.js:239:14)
    at Object.module.exports.cli.runCommand (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc/cli.js:189:5)
    at /Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/Users/myrmel/Documents/LocalDev/webv2/node_modules/jsdoc/jsdoc.js:106:3)`

**Comment by Kocal** [comment]
Hi,

Unfortunately, the plugin doesn't use webpack config file, so the plugin doesn't know what is an alias or not, and so it's failing for your usage case.

Also, i don't want to make webpack running on VueJS project, because I will probably lost jsdoc comment and I will be unable to run JSDoc on it... 

I'm thinking about it!

**Comment by awmottaz** [comment]
Is it possible to at least make it optional whether this plugin will follow the import paths? Can you just treat them like a black box and document the code that is actually present in the `.vue` file?

**Comment by Kocal** [comment]
Mmmh yea why not. 

I see something like that for JSDoc config:

```json
{
  "plugins": [
    "node_modules/jsdoc-vuejs"
  ],
  "vuejs": {
    "followRequire": false, 
   },
  "source": {
    "includePattern": "\\.(vue|js)$"
    // or
    "include": [
       "foo.vue",
       "bar/test.vue'
    ]
  }
}
```

Also, I need to modify [lib/vueComponentPrototypeExtractor.js](lib/vueComponentPrototypeExtractor.js). 
I will work on that this week-end I think

**Comment by Kocal** [comment]
Check the new 1.0.11 version, you can choose to follow imports or not (https://github.com/Kocal/jsdoc-vuejs#usage)

**Comment by MyrtoM** [comment]
Thank you so much, this is great, very usefull !
